# Project information
site_name: MetaDhana Whitepaper (draft)
site_url: https://whitepaper.metadhana.io
extra:
    homepage: https://www.metadhana.io
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
  palette: #1
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: red
    - scheme: slate #2
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: purple
      accent: pink
  favicon: assets/favicon.png
  logo: assets/logo.png
nav:
  # Overview for MetaDhana
  - Overview:
      - overview/for-our-community.md
      - Ecosystem & Technology: overview/technology.md
      - overview/roadmap.md
      - overview/team-partners.md
  # MetaDhana DAO with own Roadmap
  - MetaDhana DAO:
      - dao/README.md
      - DAO Architecture:
          - dao/architecture/README.md
          - dao/architecture/treasury.md
          - dao/architecture/tokens.md
      - DAO Utilities:
          - dao/utilities/staking.md
          - dao/utilities/gaming.md
          - dao/utilities/media-consumption.md
          - dao/utilities/governance.md
      - Tokenomics:
          - dao/tokenomics/README.md
          - dao/tokenomics/sale-rounds.md
          - dao/tokenomics/presale-token.md
      - dao/roadmap.md
      - dao/smart-contracts.md
  # MetaDhana DAO with own Roadmap (Release of next Race?)
  - Metazoan Chronicles:
      - metazoan/README.md
      - Felisian Race:
          - metazoan/felisians/README.md #Genesis, Parent-Child
          - Classes:
              - metazoan/felisians/class/README.md
              - metazoan/felisians/class/t3.md
              - metazoan/felisians/class/t2.md
              - metazoan/felisians/class/t1.md
              - metazoan/felisians/class/t0.md
          - Rarity Layers:
              - metazoan/felisians/rarity/README.md
          - Minting Rounds:
              - metazoan/felisians/minting/README.md #Minting Rounds
      - NFT Utilities (Felisian):
          - metazoan/nft-utility/README.md
          - metazoan/nft-utility/play-to-earn.md
          - metazoan/nft-utility/scholarships.md
          - metazoan/nft-utility/ai.md
      - Game Mechanics:
          - metazoan/game-mechanics/README.md
      - metazoan/smart-contracts.md

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - redirects:
        redirect_maps:
            'index.md': 'overview/for-our-community.md'