# Project information
site_name: MetaDhana Litepaper
site_url: https://whitepaper.metadhana.io
extra:
  homepage: https://www.metadhana.io
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
  palette: #1
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black
      accent: deep orange
    - scheme: slate #2
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: amber
  favicon: assets/favicon.png
  logo: assets/logo.png
nav:
  # Overview for MetaDhana
  - For Our Community: README.md
  - Ecosystem & Technology: technology.md
  - Value Generation:
      - DestineX DAO: value/value-generation.md
  - Games and Game Partners:
      - In House: games/house.md
      - Partners: games/game-partners.md
  - Additional Details:
      - Roadmap: details/roadmap.md
      - Team & Partners: details/team-partners.md

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
