site_name: MetaDhana Studio
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
  palette: #1
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: red
    - scheme: slate #2
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: purple
      accent: pink
nav:
  - Home:
      - home/for-our-community.md
      - home/dao.md
      - home/metazoan.md
      - home/technology.md
      - home/roadmap.md
      - home/team-partners.md
  - metazoan-chronicles.md
  - Felisian Race:
      - felisians/README.md #Genesis, Parent-Child
      - Classes:
          - felisians/class/README.md
          - felisians/class/t3.md
          - felisians/class/t2.md
          - felisians/class/t1.md
          - felisians/class/t0.md
      - Rarity Layers:
          - felisians/rarity/README.md
      - Minting Rounds:
          - felisians/minting/README.md #Minting Rounds
  - NFT Utilities (Felisian):
      - nft-utility/README.md
      - nft-utility/play-to-earn.md
      - nft-utility/scholarships.md
      - nft-utility/ai.md
  - Game Mechanics:
      - game-mechanics/README.md
  - MetaDhana DAO:
      - dao/README.md
      - dao/treasury.md
      - dao/tokens.md
      - DAO Utilities:
          - dao/utilities/staking.md
          - dao/utilities/gaming.md
          - dao/utilities/media-consumption.md
          - dao/utilities/governance.md
  - Tokenomics:
      - tokenomics/README.md
      - tokenomics/sale-rounds.md
      - tokenomics/presale-token.md
  - technology.md
  - smart-contracts.md

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
