site_name: Metazoan Chronicles (Draft)
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
  palette: #1
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: red
    - scheme: slate #2
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: purple
      accent: pink
nav:
  - README.md
  - metazoan-chronicles.md
  - Felisian Race:
      - felisians/README.md #Genesis, Parent-Child
      - Classes:
          - felisians/class/README.md
          - felisians/class/t3.md
          - felisians/class/t2.md
          - felisians/class/t1.md
          - felisians/class/t0.md
      - Rarity Layers:
          - felisians/rarity/README.md
      - Minting Rounds:
          - felisians/minting/README.md #Minting Rounds
  - NFT Utilities (Felisian):
      - nft-utility/README.md
      - nft-utility/play-to-earn.md
      - nft-utility/scholarships.md
      - nft-utility/ai.md
  - Game Mechanics:
      - game-mechanics/README.md
  - Tokens:
      - tokens/README.md #Main Token
      - tokens/game-token.md
      - tokens/presale-token.md
      - tokens/staking-token.md
  - DeFI 2.0:
      - defi/README.md
      - defi/staking.md
      - defi/marketplace.md
      - defi/swap.md
  - technology.md
  - roadmap.md
  - team-and-partners.md
  - smart-contracts.md

markdown_extensions:
  - attr_list
  - md_in_html
